#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/magicsack
  
  rm -rf build/* tmp/* 
  
  pySloc -L py  -X cover -X htmlcov -X dist -v $@ src/magicsack src/magicSack tox.ini requirements.txt test_requirements.txt tests/test_puzzle.py setup.py
else
  echo "DEV_BASE is not defined"
fi
