#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/magicsack
  
  autopep8 -ai -r src/magicsack 
  autopep8 -ai src/magicSack tests/*.py
  
else
  echo "DEV_BASE is not defined"
fi
