[meta]
version = "0.1.0"

[project]
name = "magicsack"
package = "magicsack"
main_lang = "py"
version = "0.4.13"
version_date = "2018-03-07"
author = "Jim Dixon"
author_email = "jddixon@gmail.com"
description = "generator for magicsack projects"
copyright = "2014-2017"
dev_status = "pre-alpha"
license = "mit"
relpath = "py/magicsack"
state = "shared"
url = "https://jddixon.github.io/magicsack"

[py]
packages = [ "magicsack",]
package_dir = [ "src",]
test_dir = "tests"
py_modules = []
scripts = [ "src/magicSack",]
ext_modules = []
distshare = [ "buildlist", "nlhtree_py", "optionz", "rnglib", "xlattice_py",]
requirements = [ "pycrypt", "pbkdf2", "scandir", "setuptools",]
test_requirements = []
